name: Robert Wade
favicon: null
layout_spectrum: 0.8637413601391017
typography_spectrum: 0.29905051249079406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6307004522532225
  lightness: 0.7096745618619025
  saturation: 0.9944049676414579
  rhythmicContrast: 0.869515749393031
purpose: []
